### ISSUE TITLE
common.sh downloads older version of statAP script

### ISSUE THREAD

**Issue by arjenpdevries** [lintool/IR-Reproducibility#23]
Hi,

The `common.sh` shell script downloads `v3` of the statAP script, but I think there is a newer one here:
https://trec.nist.gov/data/blog/10/statAP_MQ_eval_v4.pl

Not sure if you would want to have both versions or just replace the older one with this one.

Greetings,

Arjen

**Comment by lintool** [comment]
Hi @arjenpdevries we're no longer actively maintaining this repo, but planning for the next Docker-based iteration, so I'm going to leave alone and close the issue. Thanks for reporting though!

**Comment by arjenpdevries** [comment]
Maybe put a no longer maintained msg in the README.md?

Cheers!
