### ISSUE TITLE
Refactoring of Galago scripts

### ISSUE THREAD

**Issue by lintool** [lintool/IR-Reproducibility#5]
https://github.com/lintool/IR-Reproducibility/blob/master/systems/galago/dotgov2.sh#L7
At some point, grab a stable version?

https://github.com/lintool/IR-Reproducibility/blob/master/systems/galago/dotgov2.sh#L8
Can you just use . for tmp? I.e., let's avoid absolute paths and paths outside the repo?

Java -- does something like `sudo apt-get install java` work for you?

**Comment by jjfiv** [comment]
> https://github.com/lintool/IR-Reproducibility/blob/master/systems/galago/dotgov2.sh#L7
> At some point, grab a stable version?

We generally release on the Solstice, so a stable version with all my changes will be available at the beginning of next week.

> https://github.com/lintool/IR-Reproducibility/blob/master/systems/galago/dotgov2.sh#L8
> Can you just use . for tmp? I.e., let's avoid absolute paths and paths outside the repo?

I can use something else for tmp; I just get sick of bash and the weirdness of `pwd` depending on from whence the script is run, so I tend to overuse absolute paths.

> Java -- does something like `sudo apt-get install java` work for you?

We need at least Java 7 ... some versions of Ubuntu don't have it, so I've gotten used to downloading a local copy of Oracle's JDK for my work. I'll take a look the next time I'm on the VM. I've heard (maybe unsubstantiated) rumors that the Oracle I/O libs are faster than the OpenJDK ones.

**Comment by jjfiv** [comment]
Fixed in last pull request.

**Comment by jjfiv** [comment]
Oops, except stable version. Still waiting for the release.

**Comment by lintool** [comment]
@jjfiv positional indexing still says "7h < t < 17h" I assume there's enough instrumentation for you to measure?

Should also document that SDM needs positional indexes.
